In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("survey_results_public.csv",low_memory=False)

In [9]:
pd.set_option("display.max_columns",200)

In [10]:
df.isna()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,True,True,True,False,False,True,True,True,True,False,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False,False,True,True,False,True,True,True,True,False,False,True,True,True,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,False,True,True,True,False,True,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,True,True,True,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,True,True,True,True,True,False,True,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,True,False,True,True,True,True,True,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False,False,False,False,True,True,False,True,True,True,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,True,True,True,True,True,False,True,True,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,True,True,True,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,True,True,True,True,True,True,True,False,True,False,True,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,True,True,True,True,True,True,False,True,False,False,True,True,True,True,True,True,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49187,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49188,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
49189,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
49190,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [13]:
df.dropna(axis='index',how='any',subset=['ConvertedCompYearly'])

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49098,49099,I am a developer by profession,45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Attending school (full-time);Attending school ...,8.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,6.0,DevOps engineer or professional,"1,000 to 4,999 employees",NaN,In-person,"Yes, I endorsed a tool that was ultimately not...",Work,6.0,4.0,2.0,8.0,7.0,9.0,1.0,5.0,3.0,10.0,NaN,4.0,8.0,7.0,5.0,6.0,2.0,3.0,9.0,1.0,10.0,NaN,Software Development,8.0,14.0,11.0,7.0,10.0,13.0,3.0,12.0,9.0,1.0,6.0,4.0,5.0,15.0,2.0,NaN,Yes,I have strongly considered changing my career ...,39.0,160.0,Poland,PLN Polish zloty,10000.0,Yes,Ada;Assembly;Erlang;F#;Fortran;GDScript;Go;Groovy,Ada;Assembly;Erlang;F#;Fortran;GDScript;Go;Groovy,Ada;Assembly;Erlang;F#;Fortran;GDScript;Go;Groovy,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,A few times per month or weekly,"More than 15 years, or since Stack Overflow st...",Multiple times per day,Message Boards;Long-form articles;Coding chall...,7.0,1.0,4.0,8.0,9.0,2.0,6.0,3.0,5.0,10.0,NaN,"Yes, definitely",About half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,NaN,Learning about a codebase;Project planning;Wri...,NaN,I’ve become less confident in my own problem-s...,Https,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering;Business process automati...,Multi-platform search enablement;Language proc...,NaN,NaN,NaN,AI agents have reduced the time spent on speci...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,Redis;Fireproof;LanceDB;Letta;Qdrant;GitHub MC...,GitHub,Vertex AI;Agno;AutoGen (Microsoft);CrewAI;IBM ...,NaN,Sentry;Galileo;Honeycomb;Metero;New Relic;opik...,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,NaN,When I’m stuck and can’t explain the problem,الكود المصدر الذي وجب على أساس الذكاء الاصطناعي,2729.0,NaN

In [14]:
df.fillna(0)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,0,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,0,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,0,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,0,0,Yes,Cloud Firestore;PostgreSQL,0,0,0,0,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,0,0,0,0,No,0,0,0,0,0,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,0,0,0,0,0,0,0,0,0,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,0,0,"Stack Overflow;Reddit;GitHub (public projects,...",0,0,0,0,Yes,openAI GPT (chatbot models);openAI Image gener...,0,0,0,0,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,0,1.0,0.0,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,0,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,0,0,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,0,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,0,0,0,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,0,0,0,0,Vertex AI,0,0,0,ChatGPT,0,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,0,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,0,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,0,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,0,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,0,0,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,0,0,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,0,0,Yes,Spring Boot,Spring Boot,Spring Boot,0,0,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,0,0,0,0,0,0,0,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,0,0,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,0,0,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),0,0,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,0.0,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,0,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,0,0,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,0,0,0,0,0,0,0,It takes significant time and effort to learn ...,0,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,0,0,0,0,0,0,0,0,0,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",0,0,0,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,0,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,0,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,0,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,0,0,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,0,0,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,0,0,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,0,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,0,0,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,0,0,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,0,0,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,0,0,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,0,0,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,0.0,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,0,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,0,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,0,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,0,0,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,0,I am concerned about the accuracy of the infor...,0,Redis,0,0,0,0,0,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,0,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,0,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,0,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,0,No,I have neither consider or transitioned into a...,0.0,0.0,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,0,0,No,0,0,0,0,0,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,0,0,Yes,Spring Boot,Spring Boot,Spring Boot,0,0,No,0,0,0,0,0,Amazon Bedrock,0,0,0,0,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,0,0,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,0,0,No,0,0,0,0,0,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,0.0,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,0,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,0,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,0,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,0,0,It takes significant time and effort to learn ...,0,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,0,0,0,0,0,0,0,ChatGPT;Claude Code,0,When I don’t trust AI’s answers;When I want to...,0,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",0,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,0,0,0,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,0,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,0,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,0,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,0,0,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,0,0,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,0,0,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,0,0,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,0,0,Large Language Model;Google Gemini,Large Language Model,Large Language Model,0,0,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,0,0,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,0,0,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),0,0,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,0.0,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,0,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,0,0,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",0,0,0,0,0,0,0,Integrating AI agents with my existing tools a...,0,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,0,0,0,0,0,0,0,0,0,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,0,0.0,0,0,0,0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,0,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,0,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,0,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,0,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,0,0,0,0,0,0,AI agents have increased my productivity.,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",0,0.0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [17]:
df["ConvertedCompYearly"].unique()

array([ 61256., 104413.,  53061., ..., 138470.,   5825.,  69008.],
      shape=(6238,))

In [18]:
df["ConvertedCompYearly"].unique().tolist()

[61256.0,
 104413.0,
 53061.0,
 36197.0,
 60000.0,
 120000.0,
 6240.0,
 72000.0,
 70000.0,
 5400.0,
 65691.0,
 14400.0,
 1099.0,
 nan,
 16252.0,
 87500.0,
 108913.0,
 162421.0,
 209643.0,
 78000.0,
 205000.0,
 250000.0,
 175000.0,
 95132.0,
 109000.0,
 91215.0,
 150000.0,
 99999.0,
 270000.0,
 43810.0,
 80966.0,
 28275.0,
 142949.0,
 117793.0,
 75410.0,
 81210.0,
 63909.0,
 151000.0,
 83531.0,
 46406.0,
 6000.0,
 62767.0,
 151117.0,
 67289.0,
 197225.0,
 245000.0,
 14850.0,
 3.0,
 75472.0,
 174022.0,
 210788.0,
 115720.0,
 20677.0,
 72958.0,
 1480.0,
 5000.0,
 13615.0,
 116000.0,
 87011.0,
 90000.0,
 36407.0,
 139218.0,
 25523.0,
 13649.0,
 1.0,
 81685.0,
 58007.0,
 167061.0,
 195000.0,
 8509.0,
 145018.0,
 155000.0,
 80254.0,
 109438.0,
 87561.0,
 75000.0,
 88492.0,
 131000.0,
 2157.0,
 15546.0,
 48726.0,
 41765.0,
 71499.0,
 45000.0,
 65663.0,
 113085.0,
 94235.0,
 440856.0,
 2900.0,
 295000.0,
 113694.0,
 80000.0,
 350000.0,
 39445.0,
 20109.0,
 43375.0,
 4873.0,
 87000.0,
 66017.0,
 27844.0,
 13922.0,
 185000.0,
 114981.0,
 130992.0,
 200000.0,
 69609.0,
 31324.0,
 91018.0,
 91899.0,
 156000.0,
 19983.0,
 165000.0,
 44086.0,
 120485.0,
 68071.0,
 98842.0,
 116015.0,
 148499.0,
 5801.0,
 17402.0,
 11530.0,
 94846.0,
 49011.0,
 8121.0,
 102142.0,
 74878.0,
 3371.0,
 129334.0,
 108000.0,
 63808.0,
 190000.0,
 8357.0,
 34804.0,
 38981.0,
 136141.0,
 152.0,
 22456.0,
 140000.0,
 1208.0,
 248250.0,
 18562.0,
 39923.0,
 220428.0,
 202416.0,
 98612.0,
 40842.0,
 260000.0,
 97682.0,
 1000.0,
 98494.0,
 135000.0,
 61996.0,
 110000.0,
 58828.0,
 81000.0,
 107894.0,
 92812.0,
 150819.0,
 51274.0,
 60518.0,
 145917.0,
 162000.0,
 117175.0,
 83857.0,
 12533.0,
 79043.0,
 52207.0,
 7656.0,
 109160.0,
 12633.0,
 223187.0,
 106190.0,
 76512.0,
 23203.0,
 106000.0,
 100000.0,
 20883.0,
 60.0,
 210000.0,
 24211.0,
 11624.0,
 127616.0,
 84277.0,
 125000.0,
 14544.0,
 164911.0,
 78890.0,
 19345.0,
 119495.0,
 58367.0,
 10133.0,
 43775.0,
 148496.0,
 163370.0,
 260.0,
 70994.0,
 214240.0,
 208000.0,
 232479.0,
 35584.0,
 99000.0,
 240000.0,
 9299.0,
 156563.0,
 12347.0,
 115304.0,
 160000.0,
 7300.0,
 80.0,
 230000.0,
 30297.0,
 59398.0,
 104000.0,
 72155.0,
 117014.0,
 275000.0,
 73688.0,
 242148.0,
 126456.0,
 201139.0,
 173250.0,
 43897.0,
 96524.0,
 71657.0,
 118443.0,
 1914.0,
 116240.0,
 300000.0,
 129936.0,
 191424.0,
 29648.0,
 18000.0,
 16664.0,
 330000.0,
 55687.0,
 185623.0,
 176984.0,
 40000.0,
 167804.0,
 40605.0,
 15036.0,
 60328.0,
 49886.0,
 48132.0,
 65073.0,
 130000.0,
 67400.0,
 21816.0,
 146750.0,
 7208.0,
 127500.0,
 269154.0,
 45934.0,
 79245.0,
 13614.0,
 2400.0,
 78281.0,
 97764.0,
 17840.0,
 70208.0,
 125729.0,
 149756.0,
 9368.0,
 14563.0,
 14687.0,
 110109.0,
 24000.0,
 55511.0,
 280000.0,
 194000.0,
 66000.0,
 37554.0,
 144000.0,
 225019.0,
 99346.0,
 104822.0,
 12762.0,
 54457.0,
 218875.0,
 85039.0,
 138000.0,
 99194.0,
 800000.0,
 95000.0,
 212750.0,
 5973.0,
 5231.0,
 37125.0,
 82018.0,
 100933.0,
 107198.0,
 82283.0,
 94874.0,
 14243.0,
 376000.0,
 81.0,
 25535.0,
 15723.0,
 2221.0,
 204212.0,
 119000.0,
 275124.0,
 61264.0,
 148791.0,
 30164.0,
 61488.0,
 114038.0,
 106733.0,
 13949.0,
 237226.0,
 208826.0,
 310000.0,
 48146.0,
 2121.0,
 31372.0,
 180000.0,
 117700.0,
 89331.0,
 172000.0,
 16692.0,
 58700.0,
 220000.0,
 203026.0,
 170000.0,
 182270.0,
 233000.0,
 134000.0,
 4681.0,
 56499.0,
 294400.0,
 66824.0,
 74423.0,
 16542.0,
 121815.0,
 131200.0,
 73017.0,
 144600.0,
 83319.0,
 32484.0,
 62261.0,
 52411.0,
 273000.0,
 40056.0,
 407645.0,
 115000.0,
 93972.0,
 71929.0,
 561668.0,
 189122.0,
 450000.0,
 748890.0,
 213177.0,
 30623.0,
 93387.0,
 30000.0,
 276325.0,
 104900.0,
 77098.0,
 116733.0,
 8137.0,
 85000.0,
 38549.0,
 22.0,
 62893.0,
 105000.0,
 110214.0,
 50994.0,
 15792.0,
 40684.0,
 83902.0,
 278.0,
 35000.0,
 260385.0,
 86590.0,
 64667.0,
 149950.0,
 400000.0,
 94087.0,
 136392.0,
 217826.0,
 173590.0,
 102106.0,
 84408.0,
 272000.0,
 153213.0,
 29584.0,
 340000.0,
 132000.0,
 115666.0,
 99383.0,
 54611.0,
 202824.0,
 26683.0,
 19575.0,
 103000.0,
 255232.0,
 10800.0,
 177000.0,
 123993.0,
 35965.0,
 13962.0,
 66797.0,
 47566.0,
 106752.0,
 45840.0,
 88000.0,
 65425.0,
 128000.0,
 185989.0,
 5209.0,
 50000.0,
 55136.0,
 16383.0,
 84250.0,
 103156.0,
 50829.0,
 7149.0,
 136000.0,
 43505.0,
 48000.0,
 76000.0,
 55121.0,
 2731.0,
 133417.0,
 146000.0,
 145000.0,
 69298.0,
 91000.0,
 4882.0,
 144700.0,
 254778.0,
 83234.0,
 82000.0,
 47650.0,
 37198.0,
 2480.0,
 33886.0,
 221064.0,
 59000.0,
 65348.0,
 21605.0,
 104400.0,
 78394.0,
 88353.0,
 20.0,
 87550.0,
 61531.0,
 129671.0,
 170177.0,
 3570.0,
 36434.0,
 55714.0,
 187000.0,
 7661.0,
 20000.0,
 113000.0,
 19139.0,
 71001.0,
 9880.0,
 68225.0,
 14502.0,
 13169.0,
 74000.0,
 13107.0,
 248058.0,
 72393.0,
 12624.0,
 73100.0,
 73901.0,
 18641.0,
 91198.0,
 5161.0,
 176070.0,
 14038.0,
 59969.0,
 18424.0,
 66395.0,
 69751.0,
 25485.0,
 320000.0,
 171702.0,
 48239.0,
 148800.0,
 59377.0,
 46111.0,
 47840.0,
 85088.0,
 51071.0,
 253000.0,
 12743.0,
 148000.0,
 97452.0,
 928117.0,
 98032.0,
 7000.0,
 12205.0,
 103468.0,
 82695.0,
 13578.0,
 67851.0,
 825000.0,
 75559.0,
 215000.0,
 50606.0,
 38671.0,
 27760.0,
 42720.0,
 113615.0,
 57861.0,
 217000.0,
 129000.0,
 77000.0,
 90491.0,
 223.0,
 68134.0,
 29146.0,
 224000.0,
 85769.0,
 11021.0,
 57000.0,
 6.0,
 58990.0,
 21844.0,
 75744.0,
 7352.0,
 19765.0,
 43664.0,
 395.0,
 140226.0,
 47.0,
 40593.0,
 735.0,
 127000.0,
 153000.0,
 17476.0,
 42924.0,
 22723.0,
 9381.0,
 33412.0,
 58252.0,
 62221.0,
 174000.0,
 29060.0,
 76484.0,
 27290.0,
 105686.0,
 638081.0,
 380000.0,
 71000.0,
 96000.0,
 225000.0,
 131097.0,
 132057.0,
 154000.0,
 9818.0,
 15000.0,
 35949.0,
 163000.0,
 55797.0,
 8100.0,
 600.0,
 31121.0,
 68581.0,
 108864.0,
 10043.0,
 375000.0,
 55748.0,
 29004.0,
 69744.0,
 111111.0,
 38216.0,
 66708.0,
 46464.0,
 727.0,
 9281.0,
 385000.0,
 105573.0,
 13192.0,
 70769.0,
 68449.0,
 126000.0,
 4177.0,
 57179.0,
 814.0,
 40048.0,
 74249.0,
 16374.0,
 64203.0,
 1438.0,
 42925.0,
 85851.0,
 93800.0,
 37591.0,
 105424.0,
 106717.0,
 22108.0,
 76570.0,
 160508.0,
 122527.0,
 85536.0,
 73536.0,
 221402.0,
 5727.0,
 50118.0,
 3241.0,
 79779.0,
 62648.0,
 67655.0,
 7803.0,
 188000.0,
 192500.0,
 65500.0,
 2320.0,
 51038.0,
 71168.0,
 252000.0,
 64000.0,
 87058.0,
 116700.0,
 132192.0,
 159049.0,
 15082.0,
 102000.0,
 56490.0,
 52308.0,
 62015.0,
 3787.0,
 11500.0,
 75183.0,
 29183.0,
 84628.0,
 111975.0,
 35169.0,
 131570.0,
 112534.0,
 16706.0,
 81761.0,
 136450.0,
 5513.0,
 116212.0,
 255000.0,
 71134.0,
 73000.0,
 140417.0,
 60755.0,
 89000.0,
 96660.0,
 646.0,
 98827.0,
 50759.0,
 44480.0,
 15111.0,
 151995.0,
 11601.0,
 77730.0,
 130474.0,
 81870.0,
 66392.0,
 33644.0,
 38598.0,
 29409.0,
 109054.0,
 780000.0,
 133419.0,
 54000.0,
 23710.0,
 123000.0,
 31583.0,
 142269.0,
 99223.0,
 111636.0,
 62257.0,
 103253.0,
 4545.0,
 157000.0,
 34872.0,
 8182.0,
 176485.0,
 102093.0,
 24749.0,
 1910.0,
 8271.0,
 15300.0,
 95299.0,
 117168.0,
 7296.0,
 76800.0,
 413.0,
 46924.0,
 140023.0,
 24575.0,
 54633.0,
 11233.0,
 73089.0,
 47856.0,
 7977.0,
 99773.0,
 145600.0,
 17558.0,
 7536.0,
 118613.0,
 12060.0,
 84.0,
 24878.0,
 76729.0,
 44043.0,
 190598.0,
 100745.0,
 146329.0,
 500000.0,
 41.0,
 8000.0,
 27306.0,
 94339.0,
 69414.0,
 347180.0,
 5241.0,
 127677.0,
 251706.0,
 208562.0,
 87462.0,
 1162.0,
 83280.0,
 116943.0,
 83792.0,
 216000.0,
 12014.0,
 480000.0,
 59916.0,
 58946.0,
 53367.0,
 3480.0,
 26322.0,
 91652.0,
 49146.0,
 122976.0,
 29758.0,
 41596.0,
 49306.0,
 24363.0,
 221000.0,
 167.0,
 99193.0,
 141188.0,
 4438.0,
 10391.0,
 166000.0,
 495.0,
 47932.0,
 95980.0,
 22937.0,
 58429.0,
 39521.0,
 100807.0,
 594.0,
 3870.0,
 112334.0,
 7556.0,
 142000.0,
 33219.0,
 83200.0,
 8237.0,
 22826.0,
 62000.0,
 150818.0,
 76606.0,
 89183.0,
 581.0,
 161191.0,
 21056.0,
 87267.0,
 51864.0,
 5132.0,
 84568.0,
 79062.0,
 264728.0,
 3947.0,
 92000.0,
 105966.0,
 139.0,
 120381.0,
 54580.0,
 66128.0,
 34122.0,
 183000.0,
 44417.0,
 101167.0,
 114500.0,
 174665.0,
 93886.0,
 113815.0,
 14727.0,
 2107.0,
 46393.0,
 58382.0,
 150.0,
 56847.0,
 1006403.0,
 66038.0,
 36000.0,
 77736.0,
 201000.0,
 105353.0,
 182396.0,
 4293.0,
 111374.0,
 44927.0,
 1149.0,
 14987.0,
 285000.0,
 55.0,
 181000.0,
 29951.0,
 74418.0,
 125296.0,
 9532.0,
 57437.0,
 65237.0,
 81835.0,
 176131.0,
 130637.0,
 36479.0,
 55223.0,
 55094.0,
 1044132.0,
 118000.0,
 414000.0,
 166200.0,
 200635.0,
 17256.0,
 23759.0,
 66709.0,
 168000.0,
 117600.0,
 71279.0,
 69000.0,
 16274.0,
 580000.0,
 72815.0,
 136268.0,
 36758.0,
 66423.0,
 65528.0,
 364792.0,
 179790.0,
 96377.0,
 84691.0,
 88960.0,
 235000.0,
 73527.0,
 214627.0,
 42921.0,
 55000.0,
 122936.0,
 114545.0,
 72160.0,
 150588.0,
 3720.0,
 115085.0,
 153796.0,
 144400.0,
 371979.0,
 59927.0,
 34587.0,
 14199.0,
 31809.0,
 42000.0,
 183500.0,
 131325.0,
 12093.0,
 118593.0,
 7021.0,
 22555.0,
 36296.0,
 79570.0,
 80050.0,
 212640.0,
 31385.0,
 1400.0,
 16617.0,
 89739.0,
 131445.0,
 102972.0,
 3451.0,
 44210.0,
 53436.0,
 15175.0,
 66182.0,
 22086.0,
 198447.0,
 11000.0,
 193744.0,
 63247.0,
 3600.0,
 125250.0,
 200090.0,
 37705.0,
 179823.0,
 28398.0,
 136432.0,
 297000.0,
 69310.0,
 399.0,
 26198.0,
 37500.0,
 84632.0,
 2283.0,
 121000.0,
 26451.0,
 26795.0,
 41586.0,
 36.0,
 116122.0,
 133676.0,
 142592.0,
 115717.0,
 61285.0,
 83212.0,
 120021.0,
 325000.0,
 585000.0,
 82910.0,
 101088.0,
 115648.0,
 16327.0,
 58541.0,
 47423.0,
 4989.0,
 26320.0,
 61420.0,
 11766.0,
 43280.0,
 156860.0,
 56604.0,
 89853.0,
 95942.0,
 125534.0,
 73683.0,
 30118.0,
 47105.0,
 96494.0,
 156620.0,
 72927.0,
 118335.0,
 5197.0,
 125290.0,
 64736.0,
 17634.0,
 20727.0,
 10194.0,
 54527.0,
 196988.0,
 21857.0,
 31322.0,
 100683.0,
 52.0,
 68910.0,
 26000.0,
 63616.0,
 8457.0,
 80323.0,
 77085.0,
 102400.0,
 240970.0,
 4074.0,
 205379.0,
 43297.0,
 97514.0,
 149565.0,
 84512.0,
 65000.0,
 73.0,
 135530.0,
 90.0,
 7657.0,
 87341.0,
 122753.0,
 70554.0,
 10000.0,
 106269.0,
 23742.0,
 60038.0,
 112000.0,
 55346.0,
 109222.0,
 1300000.0,
 115707.0,
 81318.0,
 211782.0,
 25755.0,
 340980.0,
 112580.0,
 52946.0,
 58.0,
 3275.0,
 172199.0,
 18204.0,
 45246.0,
 38388.0,
 98022.0,
 ...]

In [20]:
df["ConvertedCompYearly"].median()

np.float64(75320.0)

In [32]:
df["YearsCode"].unique()

array([ 14.,  10.,  12.,   5.,  22.,  20.,  13.,  30.,  15.,   9.,   6.,
        nan,   3.,  40.,   8.,  45.,  35.,  11.,   7.,  47.,  41.,  36.,
        23.,  29.,  26.,  25.,  38.,  21.,  19.,  18.,  16.,   4.,  17.,
        42.,  27.,  24.,   2.,  28.,  37.,  32.,   1.,  39.,  53.,  33.,
        50.,  48.,  44.,  31.,  46.,  43.,  49.,  52.,  34.,  51.,  58.,
        57.,  54.,  63.,  60.,  55.,  65., 100.,  99.,  56.,  69.,  90.,
        61.,  67.,  75.,  64.,  98.,  68.,  89.,  62.,  78.,  70.,  76.,
        82.,  59.])

In [33]:
df['YearsCode'] = df['YearsCode'].astype(float)

In [34]:
df['YearsCode'].agg(["mean","median"])

mean      16.570861
median    14.000000
Name: YearsCode, dtype: float64