In [1]:
import pandas as pd

In [55]:
df=pd.read_csv("Melbourne_housing_prices.csv")
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [57]:
df.shape

(34857, 21)

In [58]:
cols_to_drop = ['Address','SellerG','Date','Postcode','CouncilArea','Lattitude','Longtitude','Method','Type','Regionname','Propertycount']
df = df.drop(columns=cols_to_drop)

In [59]:
df.head()

,Suburb,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
0,Abbotsford,2,NaN,2.5,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,1480000.0,2.5,2.0,1.0,1.0,202.0,NaN,NaN
2,Abbotsford,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0
3,Abbotsford,3,NaN,2.5,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0

In [60]:
df.isna().sum()

Suburb              0
Rooms               0
Price            7610
Distance            1
Bedroom2         8217
Bathroom         8226
Car              8728
Landsize        11810
BuildingArea    21115
YearBuilt       19306
dtype: int64

In [61]:
df = df.dropna(subset=['Price'])

In [62]:
df.isna().sum()

Suburb              0
Rooms               0
Price               0
Distance            1
Bedroom2         6441
Bathroom         6447
Car              6824
Landsize         9265
BuildingArea    16591
YearBuilt       15163
dtype: int64

In [63]:
num_cols = ['Distance','Bedroom2','Bathroom','Car','Landsize','BuildingArea','YearBuilt']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [64]:
df.isna().sum()

Suburb          0
Rooms           0
Price           0
Distance        0
Bedroom2        0
Bathroom        0
Car             0
Landsize        0
BuildingArea    0
YearBuilt       0
dtype: int64

In [65]:
df.dropna(inplace=True)
df.isna().sum().sum()

np.int64(0)

In [66]:
check_cols = ['Bedroom2','Bathroom','BuildingArea','YearBuilt']
for col in check_cols:
    print(col, (df[col] == 0).sum())

Bedroom2 16
Bathroom 34
BuildingArea 61
YearBuilt 0

In [67]:
df = df[(df['Bedroom2'] != 0) &(df['Bathroom'] != 0) &(df['BuildingArea'] != 0)]
df.shape

(27142, 10)

In [68]:
df.describe()

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
count,27142.000000,2.714200e+04,27142.000000,27142.000000,27142.000000,27142.000000,27142.000000,27142.000000,27142.000000
mean,2.992116,1.050319e+06,11.280985,3.036991,1.453062,1.788999,566.163842,142.654496,1968.482573
std,0.954982,6.416797e+05,6.787991,0.831628,0.660532,0.867701,3058.229177,281.624664,24.533686
min,1.000000,8.500000e+04,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1196.000000
25%,2.000000,6.350000e+05,6.400000,3.000000,1.000000,1.000000,352.000000,133.000000,1970.000000
50%,3.000000,8.700000e+05,10.500000,3.000000,1.000000,2.000000,512.000000,133.000000,1970.000000
75%,4.000000,1.295000e+06,14.000000,3.000000,2.000000,2.000000,592.000000,133.000000,1970.000000
max,16.000000,1.120000e+07,48.100000,20.000000,9.000000,18.000000,433014.000000,44515.000000,2019.000000

In [69]:
(df['YearBuilt'] < 1800).sum()

np.int64(1)

In [70]:
df = df[df['YearBuilt'] >= 1800]

In [91]:
df.head()

,Suburb,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt
1,Abbotsford,2,1480000.0,2.5,2.0,1.0,1.0,202.0,133.0,1970.0
2,Abbotsford,2,1035000.0,2.5,2.0,1.0,0.0,156.0,79.0,1900.0
4,Abbotsford,3,1465000.0,2.5,3.0,2.0,0.0,134.0,150.0,1900.0
5,Abbotsford,3,850000.0,2.5,3.0,2.0,1.0,94.0,133.0,1970.0
6,Abbotsford,4,1600000.0,2.5,3.0,1.0,2.0,120.0,142.0,2014.0

DATASET DESCRIPTION:

The Melbourne Housing dataset contains information about residential properties sold in Melbourne, Australia. The dataset contains property characteristics such as the number of rooms, property type, distance from the city center, land size, building area, year built, location details, and selling information.

After preprocessing and cleaning, the dataset contains approximately 27,000 observations and 10 columns, including the target variable Price.

In [92]:
df['Suburb'].nunique()

345

DATASET OBJECTIVE:

The objective of this project is to predict house prices in Melbourne using the dataset. Multiple regression models, including Linear Regression, Ridge Regression, and Lasso Regression, will be used and compared to identify the model that provides the best predictions.

In [150]:
x=df.drop('Price',axis=1)
y=df['Price']

In [151]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder as ohe
from sklearn.preprocessing import StandardScaler as ss
from sklearn.compose import ColumnTransformer as ct

In [166]:
c=ct([('Suburb',ohe(drop='first',handle_unknown='ignore'),['Suburb']),('numerical', ss(), x.columns.drop('Suburb'))])

In [167]:
from sklearn.model_selection import train_test_split as tts

In [168]:
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2,random_state=18)

In [169]:
from sklearn.linear_model import LinearRegression as lr
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [170]:
model1=Pipeline([('preprocessor', c),('model', lr())])
model2=Pipeline([('preprocessor', c),('model', Lasso(alpha=1.0,max_iter=5000))])
model3=Pipeline([('preprocessor', c),('model', Ridge(alpha=1.0,max_iter=5000))])

In [171]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('Suburb',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['Suburb']),
                                                 ('numerical', StandardScaler(),
                                                  Index(['Rooms', 'Distance', 'Bedroom2', 'Bathroom', 'Car', 'Landsize',
       'BuildingArea', 'YearBuilt'],
      dtype='object'))])),
                ('model', Ridge(max_iter=5000))])

MODEL COMPARISON:

Three regression models—Linear Regression, Ridge Regression, and Lasso Regression were used and compared on the Melbourne housing prices dataset. Linear Regression was used without regularization, while Ridge Regression used L2 regularization to reduce coefficient magnitudes and improve generalization. Lasso Regression used L1 regularization, which can shrink some coefficients to zero and perform feature selection.

In [172]:
model1.score(x_train,y_train)

0.6145655741674404

In [173]:
model1.score(x_test,y_test)

C:\Users\KIIT0001\miniconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

0.5957319508127099

In [174]:
model2.score(x_train,y_train)

0.6145231974082348

In [175]:
model2.score(x_test,y_test)

C:\Users\KIIT0001\miniconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

0.5965625389902394

In [176]:
model3.score(x_train,y_train)

0.6142291890392209

In [177]:
model3.score(x_test,y_test)

C:\Users\KIIT0001\miniconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

0.59728856854359

FINDINGS & INTERPRETATION:

All three models—Linear Regression, Ridge Regression, and Lasso Regression—produced similar performance with an R² score of around 0.59. This indicates that regularization did not significantly impact model accuracy, suggesting limited overfitting in the dataset. The moderate score reflects that housing prices are only partially explained by the available features, and performance is likely constrained more by feature quality than model choice.

FUTURE STEPS:

Future improvements could focus on feature engineering, such as creating more location-based or interaction features, applying log transformation to the target variable, and handling outliers more effectively. Additionally, experimenting with more advanced models like Random Forest or Gradient Boosting could help capture non-linear relationships and potentially improve predictive performance.

REFERENCES:

Help from online resources and ai has been taken in taking guidance and adding general
descriptions