In [8]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split as tts
import pandas as pd

In [18]:
dataset=load_digits(as_frame=True)
df=dataset.frame
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [20]:
x_train,x_test,y_train,y_test=tts(dataset.data,dataset.target,test_size=0.2,random_state=15)

In [32]:
from sklearn.linear_model import LogisticRegression as lr
from sklearn.svm import SVC as svm
from sklearn.ensemble import RandomForestClassifier as rfc 
from sklearn.tree import DecisionTreeClassifier as dtc 
from sklearn.naive_bayes import GaussianNB as gnb
from sklearn.naive_bayes import MultinomialNB as mnb
from sklearn.model_selection import GridSearchCV as gsc

In [37]:
model_params={
    'svm':{
        'model':svm(gamma='auto'),
        'params':{
            'C':[1,10,100],
            'kernel':["rbf","linear"]
        }
    },
    'random_forest': {
        'model': rfc(),
        'params' : {
            'n_estimators': [1,50,100]
        }
    },
    'logistic_regression' : {
        'model': lr(max_iter=1000),
        'params': {
            'C': [1,5,10]
        }
    },
    'decision_tree': {
        'model': dtc(),
        'params': {
            'criterion': ['gini', 'entropy'],
            'max_depth': [3, 5, 10, None]
        }
    },
    'gaussian_nb': {
        'model': gnb(),
        'params': {
            'var_smoothing': [1e-9, 1e-8, 1e-7]
        }
    },
    'multinomial_nb': {
        'model': mnb(),
        'params': {
            'alpha': [0.1, 0.5, 1.0, 2.0]
        }
    }
}

In [38]:
scores=[]
for model,mp in model_params.items():
    c=gsc(mp["model"],mp["params"],cv=5)
    c.fit(x_train,y_train)
    scores.append({
        'model': model,
        'best_score': c.best_score_,
        'best_params': c.best_params_
    })
df1=pd.DataFrame(scores)
df1

                 model  best_score                               best_params
0                  svm    0.974954              {'C': 1, 'kernel': 'linear'}
1        random_forest    0.972167                     {'n_estimators': 100}
2  logistic_regression    0.959652                                  {'C': 1}
3        decision_tree    0.843421  {'criterion': 'gini', 'max_depth': None}
4          gaussian_nb    0.853158                  {'var_smoothing': 1e-07}
5       multinomial_nb    0.900474                            {'alpha': 1.0}